---
- hosts: lampservers
  become: true
  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Install MySQL server and client
      apt:
        name:
          - mysql-server
          - mysql-client
        state: present

    - name: Install PHP and required extensions
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - php
          - libapache2-mod-php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc

    - name: Start Apache web server
      service:
        name: apache2
        state: started

    - name: Start MySQL server
      service:
        name: mysql
        state: started
